[project]
name = "your-streamlit-app"
requires-python = ">=3.9,<3.10"
dependencies = [
    "streamlit>=1.45.0",
    "rich",
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
